name: Build and Test Fullstack Application

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      #####################################
      # Checkout repository
      #####################################
      - name: Checkout repository
        uses: actions/checkout@v4

      #####################################
      # Setup Java for Backend (Spring Boot)
      #####################################
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.m2/repository
            !~/.m2/repository/org/apache/maven/plugins/maven-surefire-plugin
          key: ${{ runner.os }}-maven-${{ hashFiles('backend/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build Spring Boot Backend
        working-directory: ./backend
        run:  mvn clean install -DskipTests

      #####################################
      # Setup Node.js for Frontend (React)
      #####################################
      - name: Cache Node modules
        uses: actions/cache@v4
        with:
          path: frontend/movies_jpa_frontend/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('frontend/movies_jpa_frontend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Frontend Dependencies
        working-directory: ./frontend/movies_jpa_frontend
        run: npm install

      - name: Build React Frontend
        working-directory: ./frontend/movies_jpa_frontend
        run: npm ci

      #####################################
      # Run Tests for Backend and Frontend
      #####################################
      # - name: Run Backend Tests
      #   working-directory: ./backend
      #   run: mvn test

      # - name: Run Frontend Tests
      #   working-directory: ./frontend
      #   run: npm test -- --watchAll=false

      #####################################
      # Optional: Deploy (example placeholder)
      #####################################
      # - name: Deploy Application
      #   run: echo "Deploying application..."
